version: "3.9"

services:
  web_api:
    build:
      context: .
      target: build
    volumes:
      - .:/web
    command: /web/gradlew bootRun
    ports:
      - "8080:8080"

  tests:
    build:
      context: .
      target: build
    volumes:
      - .:/test
    command: /test/gradlew cleanTest test
